### ISSUE TITLE
Warning message at start up (Node 16.17.0)

### ISSUE THREAD

**Issue by shubhendumadhukar** [mynaparrot/plugNmeet-sdk-js#21]
There seems to be a minor issue, which doesn't break any functionality but does show up as a warning.

Message:
`(node:2975) [DEP0128] DeprecationWarning: Invalid 'main' field in './node_modules/plugnmeet-sdk-js/package.json' of 'src/index.ts'. Please either fix that or report it to the module author`

**Comment by shubhendumadhukar** [comment]
With 1.2.0, `require` doesn't seem to work as shown in the example in readme. Is this an intended change to only support `import` (esm)?

Error message:
`require() of ES Module /<project_path>/node_modules/plugnmeet-sdk-js/index.js from /<file_path> not supported.`
`Instead change the require of ....to a dynamic import() which is available in all CommonJS modules.`

**Comment by jibon57** [comment]
I've pushed new version. Please give another try again.

**Comment by shubhendumadhukar** [comment]
Works now. Thanks!
